export const ACTIVE_PLATFORMS = {
  nation: {
    name: 'THE NATION',
    tableName: 'nation_inquiries',
    source: 'nation-direct-form',
    accent: '#D8B45C',
    eyebrow: 'GOVERNANCE · COMMUNITY · ECONOMIC DEVELOPMENT',
    headline: 'Build the framework. Join the work.',
    description: 'A developing governance and community-building initiative focused on organization, culture, enterprise, land, education and shared infrastructure.',
    disclaimer: 'A submission is an inquiry or application only. It does not itself confer citizenship, tribal enrollment, government recognition, legal status, benefits, land rights or financial rights.',
    forms: {
      citizenship: ['Citizenship Interest', 'Request information about the developing citizenship and eligibility framework.'],
      membership: ['Membership Interest', 'Share your interest in participating in Nation programs, chapters or community work.'],
      'tribal-inquiry': ['Tribal & Nation Inquiry', 'Start a respectful conversation about tribal, nation or community collaboration.'],
      business: ['Business Registration Interest', 'Submit a business, enterprise or economic-development inquiry.'],
      tokens: ['Currency & Token Interest', 'Request information about future compliant currency, token or member-value programs.'],
      donate: ['Donation Interest', 'Request verified giving instructions or discuss an in-kind contribution.'],
      sponsor: ['Sponsorship', 'Propose a sponsorship, activation or institutional relationship.'],
      volunteer: ['Volunteer', 'Apply to support programs, events, outreach or operations.'],
      personnel: ['Government & Personnel Interest', 'Express interest in serving on a working group, board, department or operating team.'],
      'request-information': ['Request Information', 'Ask a general question and route it to the correct Nation workstream.'],
      'create-account': ['Account Access Interest', 'Request access to future member and stakeholder platforms.'],
    },
  },
  tribe: {
    name: 'THE TRIBE',
    tableName: 'tribe_inquiries',
    source: 'tribe-direct-form',
    accent: '#C98B4A',
    eyebrow: 'PROPERTY · COMMUNITY · ENTERPRISE',
    headline: 'A place to build, operate and belong.',
    description: 'The Tribe is the developing property, community and enterprise campus supporting Nation headquarters, education, agriculture, water, offices, events and shared operations.',
    disclaimer: 'A submission is an inquiry only. It does not create a tenancy, lease, membership, property right, reservation, employment relationship or legal entitlement.',
    forms: {
      membership: ['Community Membership', 'Express interest in participating in The Tribe community and campus programs.'],
      'property-interest': ['Property & Development Interest', 'Discuss development, investment, infrastructure or property participation.'],
      'tenant-inquiry': ['Tenant Inquiry', 'Request information about offices, operating areas, commercial spaces or long-term tenancy.'],
      campground: ['Campground & Stay Interest', 'Request information about campground, RV, container-home or group-stay concepts.'],
      vendor: ['Vendor & Operator Application', 'Apply to operate food, retail, service or event activity on the campus.'],
      employment: ['Employment Interest', 'Express interest in campus operations, construction, hospitality, agriculture or administration.'],
    },
  },
  university: {
    name: 'THE UNIVERSITY',
    tableName: 'university_inquiries',
    source: 'university-direct-form',
    accent: '#6FB7C9',
    eyebrow: 'TRADES · ENTREPRENEURSHIP · WORKFORCE',
    headline: 'Train for work. Build a future.',
    description: 'A developing workforce and trade-school initiative designed around practical skills, entrepreneurship, employer partnerships and career pathways.',
    disclaimer: 'Programs, campuses, financial aid and credentials remain subject to applicable authorization, licensing and accreditation requirements. An inquiry is not admission, enrollment or an award of credit.',
    forms: {
      apply: ['Apply / Admissions Interest', 'Begin an admissions-interest profile for a future campus or program.'],
      'program-interest': ['Program Interest', 'Tell us which trade, business or workforce program you want.'],
      'financial-aid': ['Financial Support Interest', 'Request information about future scholarships, payment plans and compliant aid options.'],
      'employer-partner': ['Employer Partnership', 'Discuss hiring, apprenticeships, curriculum input or workforce sponsorship.'],
      instructor: ['Instructor Application', 'Express interest in teaching, credentialing or developing a practical program.'],
      'campus-partner': ['Campus & Expansion Partner', 'Propose a site, facility, city partnership or operating relationship.'],
    },
  },
  'hakuna-matata': {
    name: 'HAKUNA MATATA',
    tableName: 'hakuna_matata_inquiries',
    source: 'hakuna-matata-direct-form',
    accent: '#D4B87A',
    eyebrow: 'THE BOOK · DR. DORSEY',
    headline: 'Take the mindset beyond the page.',
    description: 'Order Hakuna Matata, bring Dr. Dorsey to your organization, or build a book-club, media or bulk-order relationship around the message.',
    disclaimer: 'Submitting an inquiry does not confirm inventory, pricing, appearance availability, media access or a booking. The team will confirm terms separately.',
    forms: {
      'bulk-orders': ['Bulk Orders', 'Request books for teams, schools, conferences, companies or community groups.'],
      speaking: ['Speaking & Appearance', 'Request Dr. Dorsey for a keynote, conversation, signing or private appearance.'],
      'book-club': ['Book Club & Curriculum', 'Request a guided discussion, group reading or curriculum partnership.'],
      media: ['Media & Press', 'Request an interview, review copy, feature, podcast or press conversation.'],
      'general-inquiry': ['Book Inquiry', 'Ask a general question about Hakuna Matata or related products.'],
    },
  },
};

export function getActivePlatform(slug) {
  return ACTIVE_PLATFORMS[slug] || null;
}
